logging:
   config: classpath:log4j2.xml
env: dev
spring:
   dataSource:
      master:
         driverClassName: com.mysql.jdbc.Driver
         url: jdbc:mysql://172.16.8.48:3306/wangjun?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
         username: root
         password: 123456
         initialSize: 20
         minIdle: 5
         maxActive: 30
         maxWait: 30000
         removeAbandoned: true
         removeAbandonedTimeoutMillis: 300000
         defaultAutoCommit: false
         timeBetweenEvictionRunsMillis: 60000
         minEvictableIdleTimeMillis: 300000
         validationQuery: SELECT 1
         testWhileIdle: true
         connectionInitSql: set names utf8mb4

   redis:
#      cluster:
#         clusterNodes: 172.18.103.198:6379
#         password: xatwsz.com
#         expireSeconds: 120
#         commandTimeout: 10000  #redis操作的超时时间
#         pool:
#           maxActive: 8
#           maxWait: 1000
#           maxIdle: 8
#           minIdle: 2
      noCluster:
         database: 9
         host: 172.18.103.198
         port: 6379
         password: xatwsz.com
         maxActive: 8
         maxWait: 3000
         maxIdle: 8
         minIdle: 2
         timeout: 1000
         testOnBorrow: true
#短信验证码
sms:
   account: N7542603
   password: c9A6NX3ST50cab
   url: http://smssh1.253.com/msg/send/json
#订单签名盐值
rechargeSecret: recharge-xatwsz.com
